config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'persons/profile', as: 'user_root'
    resources :rooms
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "rooms#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :room
  enum area: { airbnb: 0}.freeze
end

app/models/room.rb
class Room < ApplicationRecord
  validates :name,:link, presence: true

  has_many :reviews
  has_one :user

  #  add validation for uniq link
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    root_path
  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]
  include RoomsHelper

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.where(user_id: current_user.id).includes(:reviews)
  end

  # GET /rooms/1 or /rooms/1.json
  def show
    @room
    reviews = @room.reviews.group('(EXTRACT(MONTH FROM created))::integer').order('2 ASC').count
    @reviews_count = chart_data reviews
    @cloud_words = cloud_words @room
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name,:link,:user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
  MONTHS = %w[January February March April May June July August September October November December]

  def cloud_words room
    text = ''
    room.reviews.each do |review|
      text += "#{review.comment}"
    end
    words_with_count = {}
    words_array = text.downcase.split(/\W+/)

    stop_array = %w[the with and to was my for s an that of a this it by has if but he i as am g is are yuo we they in]

    words_array.each do |word|
      next if stop_array.include?(word  )
      if words_with_count[word].present?
        words_with_count[word] += 1
      else
        words_with_count[word] = 1
      end
    end
    words_with_count.to_a
  end

  def chart_data grouped_month_review
    amount_per_months = (1..12).map { |m|  0 }
    grouped_month_review.each do |index, count|
      amount_per_months[index - 1 ] = count
    end
    amount_per_months
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestTask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.9.1/chart.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/wordcloud2.js/1.0.2/wordcloud2.min.js"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/persons/profile.html.erb
<h1>Persons#profile</h1>
<p>Find me in app/views/persons/profile.html.erb</p>

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :user_id, value: current_user.id, autofocus: true, required: true, class:'form-control' %>

  <div class="field">
    <%= form.label :name , class:'form-label'%><br />
    <%= form.text_field :name, autofocus: true, required: true, class:'form-control' %>
  </div>

  <div class="field">
    <%= form.label :link, class:'form-label' %><br />
    <%= form.url_field :link, required: true, class:'form-control' %>
  </div>


  <div>
    <%= form.submit class: 'btn btn-primary mt-3' %>

  </div>
<% end %>

app/views/rooms/_room.html.erb
<tr>
  <th scope="row"><%= room.id %></th>
  <td><%= room.name %></td>
  <td><%= room.link %></td>
  <td><%= room.reviews.count %></td>
  <td>
    <%= link_to 'Show', room, class: "btn btn-primary mb-3" %>
    <%= link_to 'Edit', edit_room_path(room), class: "btn btn-info mb-3" %>
    <%= link_to "Destroy", room_path(room), class: "btn btn-danger mb-3", data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?",
      class: 'btn btn-danger'
    }%>

  </td>
</tr>

app/views/rooms/_room_review.html.erb
<div class="col d-flex align-items-start">

  <div>
    <h3 class="fs-2">
      <div class="icon-square text-bg-light d-inline-flex align-items-center justify-content-center fs-4 flex-shrink-0 me-3" style="max-width: 50px">
        <img src="<%= review.user_picture %>" class="bi" width="100%">
      </div>
      <%= review.reviewer_name %>
    </h3>
    <h5><%= review.created %></h5>
    <p><%= review.comment %></p>
  </div>
</div>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>
<div class="col-4">
  <%= link_to "Back", { :controller => :rooms, :action => :index }, { class: "btn btn-primary mb-3" } %>
</div>
<%= render "form", room: @room %>

app/views/rooms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Rooms</h1>
<div class="col-4">
  <%= link_to "create new room", { :controller => :rooms, :action => :new }, { class: "btn btn-primary mb-3" } %>
</div>

<div id="rooms">
  <table class="table">
    <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Name</th>
      <th scope="col">Link</th>
      <th scope="col">Reviews</th>
      <th scope="col align-left">Controls</th>
    </tr>
    </thead>
    <tbody>


      <% @rooms.each do |room| %>
        <%= render room %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/rooms/new.html.erb
<h1>New room</h1>
<div class="col-4">
  <%= link_to "Back", { :controller => :rooms, :action => :index }, { class: "btn btn-primary mb-3" } %>
</div>
<%= render "form", room: @room %>

app/views/rooms/show.html.erb
<p style="color: green"><%= notice %></p>
<h2 class="pb-2 border-bottom"><%= @room.name %></h2>
    <div class="col-4">
      <%= link_to "Back", { :controller => :rooms, :action => :index }, { class: "btn btn-primary mb-3" } %>
    </div>
  <div class="row row-cols-1 row-cols-md-2 align-items-md-center g-5 py-5">
    <div class="d-flex flex-column align-items-start gap-2">
      <canvas id="myChart" width="400" height="300"></canvas>

    </div>
    <div class="row row-cols-1 row-cols-sm-2 g-4">
      <div>
        <h6 class="fw-semibold mb-0">link:</h6>
        <p class="text-muted"><%= @room.link %></p>
        <h6 class="fw-semibold mb-0">Last update was at:</h6>
        <p class="text-muted"><%= @room.updated_at.strftime("%d/%m/%Y") %></p>
        <h6 class="fw-semibold mb-0">Next Update:</h6>
        <p class="text-muted"><%= (@room.updated_at + 1.day).beginning_of_day.strftime("%d/%m/%Y") %></p>
      </div>

    </div>
  </div>

<canvas id="canvas" width="1000" height="400"></canvas>


  <h2 class="pb-2 border-bottom">Reviews</h2>
  <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">

    <% @room.reviews.each do |review| %>
      <%= render 'room_review', review:review %>
    <% end %>
  </div>
</div>

<script>
  const ctx = document.getElementById('myChart');
    const myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
            datasets: [{
                label: '# of Reviews',
                data: <%= @reviews_count %>,
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)',
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)'
                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)',
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    });


  const list = <%= @cloud_words.to_json.html_safe %>;
  WordCloud(document.getElementById('canvas'), {
      list: list,
      gridSize: Math.round(16 * 600 / 1024),
      weightFactor: function (size) {
          return Math.pow(size, 2.3) * 600 / 1024;
      },
      rotateRatio: 0.5,
      rotationSteps: 2,
      shape: 'circle',
  });
</script>